### ISSUE TITLE
Back end - in chrome

### ISSUE THREAD

**Issue by Iamdbat** [integry/livecart#4]
When the back end is left idle for a time and you come back to it and refresh - it takes a couple of minutes to do so rather than immediate - this didn't happen in 1.4 and my server spec is good - 4gb Ram - Dual processors 2.33mhz VPS

**Comment by integry** [comment]
Does this happen with other browsers as well?

**Comment by Iamdbat** [comment]
Yes it happens in Firefox and as you can't use IE for the back end I haven't tried that

**Comment by Iamdbat** [comment]
Rinalds has fixed this problem as of 22/08/11
